name: Trigger Databricks on PR

on:
  pull_request:
    types: [opened, reopened, synchronize]  # Trigger on PR creation/updates

jobs:
  trigger-databricks:
    runs-on: githubRunner

    steps:
      - name: Trigger Azure Databricks job
        run: |
          curl -X POST https://<your-databricks-instance>/api/2.1/jobs/run-now \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "job_id": 491994082956907,
              "notebook_params": {
                "branch": "${{ github.ref_name }}"
              }
            }'
