name: Trigger Databricks on PR

on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]  # Trigger on PR creation/updates

jobs:
  trigger-databricks:
    runs-on: githubRunner

    steps:
      - name: Trigger Azure Databricks job
        run: |
          curl -X POST https://adb-3991471668185668.8.azuredatabricks.net/api/2.1/jobs/run-now \
            -H "Authorization: Bearer ${{ secrets.DATABRICKS_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "job_id": 835268208617308,
              "notebook_params": {
                "branch": "${{ github.head_ref }}",
                "pr_number": "${{ github.event.pull_request.number }}"
              }
            }'
